[package]
name = "bitgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paste = "1.0.6"
num-traits = "0.2.14"
wyz = "0.5.0"